### ISSUE TITLE
Make all functions top level?

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/treecle#2]
I was thinking, it may make for a more predictable API to avoid namespaces and just have every function be top-level, e.g. `setParent()` instead of `parents.set()`. That works better when you do `import * from treecle` . What do you think @adamjanicki2?

**Comment by adamjanicki2** [comment]
I support this!

**Comment by LeaVerou** [comment]
This is also required for option 1 in #1 so I'm on it
