### ISSUE TITLE
Context is not passed around

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/treecle#9]
Just realized — the context is not actually passed around on function calls our functions are making, which means the `Treecle` class won't work properly.

**Comment by LeaVerou** [comment]
@adamjanicki2 I think I got most calls, could you have a look around and fix any calls I missed? Thx

**Comment by adamjanicki2** [comment]
Yes I can take a thorough look tomorrow

**Comment by LeaVerou** [comment]
> I think [this](https://github.com/mavoweb/treecle/blob/main/src/walk.js?rgh-link-date=2024-03-04T14%3A55%3A50Z#L22) was the only one I could find that isn't using call

We don't really need it for that, though we may want to add it to be prepared for the case that we may need it in the future. But we had some qualms about these criteria anyway.

**Comment by LeaVerou** [comment]
Seems this is resolved then.
